using Carbunql.Analysis.Parser;
using Carbunql.Clauses;
using Carbunql.Tables;
using System.Diagnostics.CodeAnalysis;

namespace Carbunql.Definitions;

public class ColumnDefinition : ITableDefinition
{
    public ColumnDefinition(ITable t, string columnName, string columnType)
    {
        Schema = t.Schema;
        Table = t.Table;
        ColumnName = columnName;
        ColumnType = ValueParser.Parse(columnType);
    }

    public ColumnDefinition(ITable t, string columnName, ValueBase columnType)
    {
        Schema = t.Schema;
        Table = t.Table;
        ColumnName = columnName;
        ColumnType = columnType;
    }

    public string Schema { get; init; }

    public string Table { get; init; }

    public string ColumnName { get; set; }

    public ValueBase ColumnType { get; set; }

    public bool IsNullable { get; set; } = false;

    public bool IsPrimaryKey { get; set; } = false;

    public bool IsUniqueKey { get; set; } = false;

    /// <summary>
    /// Postgres :(empty)
    /// MySQL    :AUTO_INCREMENT 
    /// SQLServer:IDENTITY(1,1)
    /// Oracle   :GENERATED BY DEFAULT AS IDENTITY
    /// </summary>
    public ValueBase? AutoNumberDefinition { get; set; } = null;

    public ValueBase? CheckDefinition { get; set; } = null;

    public bool IsAutoNumber { get; set; } = false;

    public ValueBase? DefaultValue { get; set; } = null;

    public IEnumerable<CommonTable> GetCommonTables()
    {
        yield break;
    }

    public IEnumerable<SelectQuery> GetInternalQueries()
    {
        yield break;
    }

    public IEnumerable<QueryParameter> GetParameters()
    {
        yield break;
    }

    public IEnumerable<PhysicalTable> GetPhysicalTables()
    {
        yield break;
    }

    public IEnumerable<Token> GetTokens(Token? parent)
    {
        yield return new Token(this, parent, ColumnName);

        foreach (var item in ColumnType.GetTokens(parent))
        {
            yield return item;
        }

        if (AutoNumberDefinition != null)
        {
            foreach (var item in AutoNumberDefinition.GetTokens(parent))
            {
                yield return item;
            }
        }

        if (IsPrimaryKey)
        {
            yield return new Token(this, parent, "primary key", isReserved: true);
        }
        else if (IsUniqueKey)
        {
            yield return new Token(this, parent, "unique", isReserved: true);
        }

        if (!IsNullable) yield return new Token(this, parent, "not null", isReserved: true);

        if (DefaultValue != null)
        {
            yield return new Token(this, parent, "default", isReserved: true);
            foreach (var item in DefaultValue.GetTokens(parent))
            {
                yield return item;
            }
        }

        if (CheckDefinition != null)
        {
            yield return new Token(this, parent, "check", isReserved: true);
            foreach (var item in CheckDefinition.GetTokens(parent))
            {
                yield return item;
            }
        }
    }

    public bool TrySet(TableDefinitionClause clause)
    {
        // Since the Column is integrated from the beginning,
        // it does not do anything, but it is treated as integrated.
        return true;
    }

    public bool TryToIndex([MaybeNullWhen(false)] out CreateIndexQuery query)
    {
        query = default;
        return false;
    }

    public bool TryNormalize([MaybeNullWhen(false)] out ColumnDefinition column)
    {
        // Exclude key information
        // Exclude check constraint
        column = new ColumnDefinition(this, ColumnName, ColumnType) { IsNullable = IsNullable, AutoNumberDefinition = AutoNumberDefinition, DefaultValue = DefaultValue };
        return true;
    }

    public bool TryDisasseble([MaybeNullWhen(false)] out IConstraint constraint)
    {
        constraint = null;
        if (CheckDefinition == null) return false;

        constraint = new CheckConstraint(this) { Value = CheckDefinition };
        return true;
    }
}
